<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lissie.Common\Lissie.Common.csproj" />
    <ProjectReference Include="..\Lissie.SmartHome\Lissie.SmartHome.csproj" />
  </ItemGroup>

</Project>
