<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Hosting.AGUI.AspNetCore" />
    <PackageReference Include="Microsoft.Agents.AI.A2A" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lissie.Common\Lissie.Common.csproj" />
    <ProjectReference Include="..\Lissie.SmartHome\Lissie.SmartHome.csproj" />
  </ItemGroup>

</Project>
