<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AGUI.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lissie.Common\Lissie.Common.csproj" />
  </ItemGroup>

</Project>
